/* ========================================================================
   CLIVEMAN 3.1  -  js/16-finale.js
   Big-font text, fireworks finale, signal-static effect, end-credits, easter-egg audio playback.

   NOTE: classic scripts sharing one global scope. Load order in
   index.html is significant - do not reorder these <script> tags.
   ======================================================================== */

const BIG_FONT_5={'A':[' ### ','#   #','#####','#   #','#   #'],'B':['#### ','#   #','#### ','#   #','#### '],'C':[' ####','#    ','#    ','#    ',' ####'],'D':['#### ','#   #','#   #','#   #','#### '],'E':['#####','#    ','#### ','#    ','#####'],'F':['#####','#    ','#### ','#    ','#    '],'G':[' ####','#    ','#  ##','#   #',' ####'],'H':['#   #','#   #','#####','#   #','#   #'],'I':['#####','  #  ','  #  ','  #  ','#####'],'J':['#####','   # ','   # ','#  # ',' ##  '],'K':['#   #','#  # ','###  ','#  # ','#   #'],'L':['#    ','#    ','#    ','#    ','#####'],'M':['#   #','## ##','# # #','#   #','#   #'],'N':['#   #','##  #','# # #','#  ##','#   #'],'O':[' ### ','#   #','#   #','#   #',' ### '],'P':['#### ','#   #','#### ','#    ','#    '],'Q':[' ### ','#   #','# # #','#  # ',' ## #'],'R':['#### ','#   #','#### ','#  # ','#   #'],'S':[' ####','#    ',' ### ','    #','#### '],'T':['#####','  #  ','  #  ','  #  ','  #  '],'U':['#   #','#   #','#   #','#   #',' ### '],'V':['#   #','#   #','#   #',' # # ','  #  '],'W':['#   #','#   #','# # #','## ##','#   #'],'X':['#   #',' # # ','  #  ',' # # ','#   #'],'Y':['#   #',' # # ','  #  ','  #  ','  #  '],'Z':['#####','   # ','  #  ',' #   ','#####'],' ':['     ','     ','     ','     ','     '],'.':['     ','     ','     ','     ','  #  '],'-':['     ','     ',' ### ','     ','     '],"'":['  #  ','  #  ','     ','     ','     ']};
function bigText(text){const up=text.toUpperCase();const rows=['','','','',''];for(let i=0;i<up.length;i++){const ch=up[i];const g=BIG_FONT_5[ch]||BIG_FONT_5[' '];for(let r=0;r<5;r++){rows[r]+=g[r]+' ';}}return rows.join('\n');}
const finaleOverlay=document.getElementById('finaleOverlay');
const fwCanvas=document.getElementById('fwCanvas');
const finaleNameEl=document.getElementById('finaleName');
const finaleSubtitleEl=document.getElementById('finaleSubtitle');
const staticOverlay=document.getElementById('staticOverlay');
const staticCanvas=document.getElementById('staticCanvas');
let fwCtx=null,fwParticles=[],fwAnimId=null,fwActive=false;
function fwResize(){fwCanvas.width=window.innerWidth;fwCanvas.height=window.innerHeight;}
function spawnFirework(x,y,color){const num=60+Math.floor(Math.random()*40);for(let i=0;i<num;i++){const angle=(Math.PI*2*i)/num+Math.random()*0.2;const speed=2+Math.random()*5;fwParticles.push({x:x,y:y,vx:Math.cos(angle)*speed,vy:Math.sin(angle)*speed,life:1.0,color:color,size:2+Math.random()*2});}if(!window._suppressFireworkBeeps){beep(880+Math.random()*400,0.25,0.06,'square');setTimeout(function(){beep(220,0.5,0.04,'sawtooth');},80);}}
function fwLoop(){if(!fwActive)return;fwCtx.fillStyle='rgba(0,0,0,0.18)';fwCtx.fillRect(0,0,fwCanvas.width,fwCanvas.height);for(let i=fwParticles.length-1;i>=0;i--){const p=fwParticles[i];p.x+=p.vx;p.y+=p.vy;p.vy+=0.06;p.life-=0.012;if(p.life<=0){fwParticles.splice(i,1);continue;}fwCtx.globalAlpha=p.life;fwCtx.fillStyle=p.color;fwCtx.shadowBlur=12;fwCtx.shadowColor=p.color;fwCtx.beginPath();fwCtx.arc(p.x,p.y,p.size,0,Math.PI*2);fwCtx.fill();}fwCtx.globalAlpha=1;fwCtx.shadowBlur=0;fwAnimId=requestAnimationFrame(fwLoop);}
function startFireworks(){fwCtx=fwCanvas.getContext('2d');fwResize();window.addEventListener('resize',fwResize);fwParticles=[];fwActive=true;fwLoop();}
function stopFireworks(){fwActive=false;if(fwAnimId)cancelAnimationFrame(fwAnimId);fwAnimId=null;}
const FW_COLORS=['#ff3366','#33ff66','#ffb000','#66ccff','#ff66ff','#ffff66','#ff9933'];
async function showFinaleName(name,subtitle){finaleNameEl.classList.remove('show');finaleSubtitleEl.classList.remove('show');await sleep(150);finaleNameEl.textContent=bigText(name);finaleSubtitleEl.textContent=subtitle||'';void finaleNameEl.offsetWidth;finaleNameEl.classList.add('show');if(subtitle)finaleSubtitleEl.classList.add('show');for(let burst=0;burst<6;burst++){const x=fwCanvas.width*(0.15+Math.random()*0.7);const y=fwCanvas.height*(0.15+Math.random()*0.5);const color=FW_COLORS[Math.floor(Math.random()*FW_COLORS.length)];spawnFirework(x,y,color);await sleep(260);}await sleep(900);}
let staticActive=false,staticAnimId=null;
function startStatic(){staticOverlay.classList.add('show');const ctx=staticCanvas.getContext('2d');staticCanvas.width=window.innerWidth;staticCanvas.height=window.innerHeight;staticActive=true;function loop(){if(!staticActive)return;const w=staticCanvas.width,h=staticCanvas.height;const img=ctx.createImageData(w,h);const d=img.data;for(let i=0;i<d.length;i+=4){const v=Math.random()*255;d[i]=v;d[i+1]=v;d[i+2]=v;d[i+3]=255;}ctx.putImageData(img,0,0);staticAnimId=requestAnimationFrame(loop);}loop();if(audioCtx){try{const noiseBuffer=audioCtx.createBuffer(1,audioCtx.sampleRate*2,audioCtx.sampleRate);const out=noiseBuffer.getChannelData(0);for(let i=0;i<out.length;i++)out[i]=(Math.random()*2-1)*0.15;const noise=audioCtx.createBufferSource();noise.buffer=noiseBuffer;noise.loop=true;const gain=audioCtx.createGain();gain.gain.value=0.12;noise.connect(gain);gain.connect(audioCtx.destination);noise.start();window._staticNoise=noise;}catch(e){}}}
function stopStatic(){staticActive=false;if(staticAnimId)cancelAnimationFrame(staticAnimId);if(window._staticNoise){try{window._staticNoise.stop();}catch(e){}}}
async function playFinale(){stopMusic();finaleOverlay.classList.add('show');startFireworks();await sleep(400);await showFinaleName('CLIVEMAN','A Text-Based Python Project (c)(R)(TM) 2019');await sleep(600);const credits=[['BEN SMITH','PROJECT MANAGER'],['RYAN PERUSKI','LEAD DEVELOPER'],['AIDAN GAROFALO','SCRUM MASTER'],['GABE GILLIS','STORY DEVELOPER']];for(let i=0;i<credits.length;i++){await showFinaleName(credits[i][0],credits[i][1]);await sleep(700);}await showFinaleName('THANK YOU','FOR PLAYING');await sleep(1400);stopFireworks();finaleNameEl.classList.remove('show');finaleSubtitleEl.classList.remove('show');await sleep(600);startStatic();}async function playFinaleEasterEgg(){const eeAudio=document.getElementById('easterEggAudio');window._suppressFireworkBeeps=true;if(eeAudio){try{eeAudio.currentTime=0;eeAudio.volume=0.6;const p=eeAudio.play();if(p&&p.catch)p.catch(function(){});}catch(e){}}finaleOverlay.classList.add('show');startFireworks();await sleep(400);await showFinaleName('CLIVEMAN','A Secret Look at the Crew');await sleep(600);const credits=[['BEN SMITH','PROJECT MANAGER'],['RYAN PERUSKI','LEAD DEVELOPER'],['AIDAN GAROFALO','SCRUM MASTER'],['GABE GILLIS','STORY DEVELOPER']];for(let i=0;i<credits.length;i++){await showFinaleName(credits[i][0],credits[i][1]);await sleep(700);}await showFinaleName('THANK YOU','FOR PEEKING');await sleep(1200);stopFireworks();finaleNameEl.classList.remove('show');finaleSubtitleEl.classList.remove('show');await sleep(600);finaleOverlay.classList.remove('show');if(eeAudio){try{eeAudio.pause();eeAudio.currentTime=0;}catch(e){}}window._suppressFireworkBeeps=false;window._easterEggCredits=false;if(cityEl&&document.body.contains(cityEl)){startCityGlimmer();startNoirMusic();}}