/* ========================================================================
   CLIVEMAN 3.1  -  js/06-prompts.js
   Player prompt primitives: ask, choice buttons, yes/no, press-any-key, number / slider input.

   NOTE: classic scripts sharing one global scope. Load order in
   index.html is significant - do not reorder these <script> tags.
   ======================================================================== */
function ask(){return new Promise(function(res){waitingFor={resolve:res};input.focus();});}function clearChoices(){choicePanelEl.innerHTML='';choicePanelEl.classList.remove('active');}function showChoiceButtons(opts){clearChoices();choicePanelEl.classList.add('active');return new Promise(function(resolve){let resolved=false;var btns=[];for(let i=0;i<opts.length;i++){(function(opt){const btn=document.createElement('button');btn.type='button';btn.className='choice-btn';btn.textContent=(window.t?window.t(opt.label):opt.label);function pick(e){if(resolved)return;resolved=true;if(e){e.preventDefault();e.stopPropagation();}document.removeEventListener('keydown',onEnter,true);ensureAudio();playKeyClick();clearChoices();instantLine('C:\\DUDLEY> '+opt.label,'input-echo');resolve(opt);}btn.addEventListener('click',pick);btn.addEventListener('touchend',pick);btn.addEventListener('touchstart',function(e){e.stopPropagation();},{passive:true});choicePanelEl.appendChild(btn);btns.push({btn:btn,pick:pick});})(opts[i]);}/* Allow Enter to trigger continue when there is only one option (e.g. CONTINUE button) */function onEnter(e){if(e.key!=='Enter'||resolved||typing)return;e.preventDefault();btns[0].pick();}document.addEventListener('keydown',onEnter,true);requestAnimationFrame(function(){scrollScreenToBottom();try{choicePanelEl.scrollIntoView({block:'nearest',behavior:'auto'});}catch(e){}});});}async function askChoice(prompt,opts){await typeLine(prompt,'sys');return await showChoiceButtons(opts);}async function askClick(prompt,opts){await typeLine(prompt,'sys');return await showChoiceButtons(opts);}async function yn(q,yesLabel,noLabel){yesLabel=yesLabel||'YES';noLabel=noLabel||'NO';await typeLine(q,'sys');const a=await showChoiceButtons([{keys:['y','yes'],label:yesLabel},{keys:['n','no'],label:noLabel},]);return a.keys.indexOf('y')!==-1;}async function pressAnyToContinue(){blank();(function(){var div=appendLine('press-continue');var kbd='  >  PRESS TO CONTINUE  <';var padTpl='  >  PRESS [{CONFIRM}] TO CONTINUE  <';div.setAttribute('data-kbd-text',kbd);div.setAttribute('data-pad-text',padTpl);var rawPad='  >  PRESS ['+labelConfirm()+'] TO CONTINUE  <';var raw=window._padConnected?rawPad:kbd;var dict=window._translations&&window._translations[window._lang||'en'];var tr=(dict&&dict[window._padConnected?padTpl:kbd])?(window._padConnected?dict[padTpl].replace(/\{CONFIRM\}/g,labelConfirm()):dict[kbd]):raw;div.textContent=tr;})();blank();
/* Allow Enter/Space to trigger CONTINUE in addition to clicking the button */
await new Promise(function(resolve){
  var done=false;
  function finish(){if(done)return;done=true;document.removeEventListener('keydown',onKey);clearChoices();ensureAudio();playKeyClick();instantLine('C:\\DUDLEY> CONTINUE','input-echo');resolve();}
  function onKey(e){
    if((e.key==='Enter'||e.key===' ')&&!typing){e.preventDefault();finish();}
  }
  document.addEventListener('keydown',onKey,{capture:true});
  /* Also show the clickable button as a backup */
  clearChoices();choicePanelEl.classList.add('active');
  var btn=document.createElement('button');
  btn.type='button';btn.className='choice-btn';
  btn.textContent=window.t?window.t('CONTINUE'):'CONTINUE';
  btn.addEventListener('click',finish);btn.addEventListener('touchend',finish);
  btn.addEventListener('touchstart',function(e){e.stopPropagation();},{passive:true});
  choicePanelEl.appendChild(btn);
  requestAnimationFrame(function(){scrollScreenToBottom();try{choicePanelEl.scrollIntoView({block:'nearest',behavior:'auto'});}catch(e){}});
});}async function askNumber(prompt,min,max){return await showSliderChoice(prompt,min,max);}async function showSliderChoice(prompt,min,max){await typeLine(prompt+' ('+min+'-'+max+')','sys');clearChoices();choicePanelEl.classList.add('active');return new Promise(function(resolve){const wrap=document.createElement('div');wrap.style.width='100%';wrap.style.textAlign='center';wrap.style.padding='8px';const valLabel=document.createElement('div');valLabel.style.color='var(--amber)';valLabel.style.fontSize='24px';valLabel.style.textShadow='0 0 6px var(--amber)';valLabel.style.marginBottom='8px';let current=Math.min(max,Math.max(min,Math.floor((min+max)/2)));valLabel.textContent='$ '+current;const slider=document.createElement('input');slider.type='range';slider.min=min;slider.max=max;slider.value=current;slider.style.width='80%';slider.style.accentColor='#ffb000';slider.addEventListener('input',function(){current=parseInt(slider.value,10);valLabel.textContent='$ '+current;});const okBtn=document.createElement('button');okBtn.type='button';okBtn.className='choice-btn';okBtn.textContent='CONFIRM BET';okBtn.style.display='block';okBtn.style.margin='12px auto 0';okBtn.addEventListener('click',function(e){e.preventDefault();ensureAudio();playKeyClick();clearChoices();instantLine('C:\\DUDLEY> Bet $'+current,'input-echo');resolve(current);});wrap.appendChild(valLabel);wrap.appendChild(slider);wrap.appendChild(okBtn);choicePanelEl.appendChild(wrap);});}